### ISSUE TITLE
使用时报错，但是不清楚是什么原因

### ISSUE THREAD

**Issue by lucky-cry** [KB5201314/autojs-unpacker#1]
Microsoft Windows [版本 10.0.18363.778]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Windows\system32>python D:\frida\autojs-unpacker-master\unpacker.py u d -p com.example.script1559346752811 -if D:/frida/autojs-unpacker-master/assets/project/01main.js -of D:/frida/autojs-unpacker-master/unmain.js
Usage: unpacker.py -m {e,d} -p PKG [other arguments]
             _        _                                        _
  __ _ _   _| |_ ___ (_)___       _   _ _ __  _ __   __ _  ___| | _____ _ __
 / _` | | | | __/ _ \| / __|_____| | | | '_ \| '_ \ / _` |/ __| |/ / _ \ '__|
| (_| | |_| | || (_) | \__ \_____| |_| | | | | |_) | (_| | (__|   <  __/ |
 \__,_|\__,_|\__\___// |___/      \__,_|_| |_| .__/ \__,_|\___|_|\_\___|_|
                   |__/                      |_|
                                                                    by: imlk
https://github.com/KB5201314/autojs-unpacker

unpacker.py: error: no such option: -i

**Comment by imlk0** [comment]
对于长参数（超过一个字母），应该使用两个横杠--if，不然会被认为是短参数
